#ifndef _IRCPARSEINTERNALS_H_
#define  _IRCPARSEINTERNALS_H_

inline __p__		(char *in, char **pr);
inline __pm__		(char *in, char **pr, char **m);
inline __pM__		(char *in, char **pr, char **m);
inline __pp__		(char *in, char **pr, char **p1);
inline __pS__		(char *in, char **pr, char **s);
inline __pP__		(char *in, char **pr, char **p1);
inline __pcF__		(char *in, char **pr, char **m,  char *f);
inline __pPt__		(char *in, char **pr, char **p1, char **t);
inline __pPm__		(char *in, char **pr, char **p1, char **m);
inline __pPM__		(char *in, char **pr, char **p1, char **m);
inline __pPS__		(char *in, char **pr, char **p1, char **s);
inline __ppp__		(char *in, char **pr, char **p1, char **p2);
inline __pbb__		(char *in, char **pr, char **p1, char **p2);
inline __ppP__		(char *in, char **pr, char **p1, char **p2);
inline __pPp__		(char *in, char **pr, char **p1, char **p2);
inline __pPP__		(char *in, char **pr, char **p1, char **p2);
inline __pPPN__		(char *in, char **pr, char **p1, char **p2, int *n1);
inline __pPcF__		(char *in, char **pr, char **p1, char **m,  char *f);
inline __pScF__		(char *in, char **pr, char **s,  char **m,  char *f);
inline __pPPT__		(char *in, char **pr, char **p1, char **p2, char **t);
inline __pPNM__		(char *in, char **pr, char **p1, int *n,    char **m);
inline __pPPm__		(char *in, char **pr, char **p1, char **p2, char **m);
inline __pPPM__		(char *in, char **pr, char **p1, char **p2, char **m);
inline __pPpp__		(char *in, char **pr, char **p1, char **p2, char **p3);
inline __pPnp__		(char *in, char **pr, char **p1, int *n,    char **p2);
inline __pPNp__		(char *in, char **pr, char **p1, int *n,    char **p2);
inline __pPPP__		(char *in, char **pr, char **p1, char **p2, char **p3);
inline __pPPNN__	(char *in, char **pr, char **p1, char **p2, int *n1,   int *n2);
inline __pPPPN__	(char *in, char **pr, char **p1, char **p2, char **p3, int *n1);
inline __pPFPN__	(char *in, char **pr, char **p1, char *t1,  char **p2, int *n1);
inline __pPScF__	(char *in, char **pr, char **p1, char **s,  char **m,  char *f);
inline __pPcFS__	(char *in, char **pr, char **p1, char **s,  char **m,  char *f);
inline __pPPcF__	(char *in, char **pr, char **p1, char **p2, char **m,  char *f);
inline __pPNNM__	(char *in, char **pr, char **p1, int *n1,   int *n2,   char **m);
inline __pPPpm__	(char *in, char **pr, char **p1, char **p2, char **p3, char **m);
inline __pPPPm__	(char *in, char **pr, char **p1, char **p2, char **p3, char **m);
inline __pPPPM__	(char *in, char **pr, char **p1, char **p2, char **p3, char **m);
inline __pPPPP__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4);
inline __pPcPPP__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4);
inline __pPcFP__	(char *in, char **pr, char **p1, char **m,  char *t1,  char **p2);
inline __pPFPP__	(char *in, char **pr, char **p1, char *t1,  char **p2, char **p3);
inline __pPPFP__	(char *in, char **pr, char **p1, char **p2, char *t1,  char **p3);
inline __pPPNNN__	(char *in, char **pr, char **p1, char **p2, int *n1,   int *n2,   int *n3);
inline __pPPPcF__	(char *in, char **pr, char **p1, char **p2, char **p3, char **m,  char *f);
inline __pPcFSF__	(char *in, char **pr, char **p1, char **m,  char *f1,  char **s,  char *f2);
inline __pPcFPF__	(char *in, char **pr, char **p1, char **m,  char *t1,  char **p2, char *t2);
inline __pPNdNPM__	(char *in, char **pr, char **p1, int *n1,   int *n2,   char **p2, char **m);
inline __pPPNNM__	(char *in, char **pr, char **p1, char **p2, int *n1,   int *n2,   char **m);
inline __pPFPFP__	(char *in, char **pr, char **p1, char *t1,  char **p2, char *t2,  char **p3);
inline __pPpppp__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4, char **p5);
inline __pPPPpp__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4, char **p5);
inline __pPPNPP__	(char *in, char **pr, char **p1, char **p2, int *n1,   char **p3, char **p4);
inline __pPPPPP__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4, char **p5);
inline __pPPcFP__	(char *in, char **pr, char **p1, char **p2, char **m,  char *f,   char **p3);
inline __pPcFNFN__	(char *in, char **pr, char **p1, char **m,  char *t1,  int *n1,   char *t2,  int *n2);
inline __pPcFPFn__	(char *in, char **pr, char **p1, char **m,  char *f1,  char **p2, char *f2,  int *n2);
inline __pPIcFNFN__	(char *in, char **pr, char **p1, char **m,  char *t1,  int *n1,   char *t2,  int *n2);
inline __pPTPTTM__	(char *in, char **pr, char **p1, char *f1,  char **p2, char *f2,  char *f3,  char **m);
inline __pPPPPFM__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4, char *t1,  char **m);
inline __pPcFPFP__	(char *in, char **pr, char **p1, char **m,  char *f1,  char **p2, char *f2,  char **p3);
inline __pPcFPoFP__	(char *in, char **pr, char **p1, char **m,  char *f1,  char **p2, char *f2,  char **p3);
inline __pPPPPPp__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4, char **p5, char **p6);
inline __pPcFNFP__	(char *in, char **pr, char **p1, char **m,  char *t1,  int *n1,   char *t2,  char **p2);
inline __pPFPPPP__	(char *in, char **pr, char **p1, char *t1,  char **p2, char **p3, char **p4, char **p5);
inline __pPPNFNM__	(char *in, char **pr, char **p1, char **p2, int *n1,   char *t1,  int *n2,   char **m);
inline __pPcFNFNF__	(char *in, char **pr, char **p1, char **m,  char *t1,  int *n1,   char *t2,  int *n2,   char *t3);
inline __pPPPPPnM__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4, char **p5, int *n,    char **m);
inline __pPPNNNNNN__	(char *in, char **pr, char **p1, char **p2, int *n1,   int *n2,   int *n3,   int *n4,   int *n5,   int *n6);
inline __pPcFPPPFP__	(char *in, char **pr, char **p1, char **m,  char *f1,  char **p2, char **p3, char **p4, char *f2,  char **p5);
inline __pPPcPPPFP__	(char *in, char **pr, char **p1, char **p2, char **m,  char **p3, char **p4, char **p5, char *t1,  char **p6);
inline __pPcFNFNFNF__	(char *in, char **pr, char **p1, char **m,  char *f1,  int *n1,   char *f2,  int *n2,   char *f3,  int *n3,  char *f4);
inline __pPPPPPPPcNp__	(char *in, char **pr, char **p1, char **p2, char **p3, char **p4, char **p5, char **p6, char **p7, char **m, int *n1, char **p8);
inline __pPFNFNPPVNNN__	(char *in, char **pr, char **p1, char *t1,  int *n1,   char *t2,  int *n2,   char **p2, char **p3, int *n3,  int *n4, int *n5, int *n6);

inline __Special__	(char *in, char **pr, char **p1, char **p2, int *n1, int *n2, char **p3, char **p4, int *n3);

#endif
